### ISSUE TITLE
Some participants added multiple times

### ISSUE THREAD

**Issue by brucejames** [ctcit/triphub#38]
In the "Tarns at Brass Monkey Biv via Lucretia" trip, Alan Ross is added multiple times.  One of him is enough :-)

![image](https://user-images.githubusercontent.com/9471192/99999404-fa6bc800-2e24-11eb-9a2f-b60ed2b316e2.png)

**Comment by nickcedwards** [comment]
I've tried to stop this from happening by making the participants table unique on `(tripId, memberId)`. This should make the database rejects any duplicate signups. For non-members, `memberId` is NULL and duplicates with NUL *are* allowed by MySQL, so that works fine.

Will leave this ticket open though, as it would be good to figure out why the front-end was adding people multiple times and prevent it from happening - there may be other unexpected behaviour caused by the same route cause.

**Comment by nickcedwards** [comment]
Closing as the issue described no longer occurs
