### ISSUE TITLE
Clicking "New Trip" while viewing a trip gives very odd behaviour

### ISSUE THREAD

**Issue by nickcedwards** [ctcit/triphub#55]
If you click "New Trip" or "New Social" while viewing a trip or social, the form is populated with details of the existing trip. On saving, any modifications are saved back to the existing trip, AND a new trip is created with the exact same details

**Comment by brucejames** [comment]
Although easily reproducible on production, this no longer happens on my development. 

The problem on production appears to be that the <Trip> component is not reconstructed during the re-render of the App component, whereas it is on development.

I suspect it was fixed when I addressed some warnings regarding missing keys on a list of items (in this case the navigation bar) by specifying unique key prefixes for the different items.  This is commit "Fixed warnings due to missing keys on list items" on 14 May 2022.

Not yet deployed to production.
